import type { CoffeeData } from "./types";

const now = new Date().toISOString();

export const seedData: CoffeeData = {
  clients: [
    {
      id: "client-capture",
      name: "Northstar Outdoor",
      notes: "Client team prefers oat milk availability and clear cup labels.",
      active: true,
      created_at: now,
    },
    {
      id: "client-agency",
      name: "Frame & Field Agency",
      notes: "Agency team often joins video village mid-morning.",
      active: true,
      created_at: now,
    },
  ],
  people: [
    {
      id: "person-noah",
      name: "Noah Kim",
      type: "crew",
      role: "Sound Mixer",
      department: "Sound",
      company: "Capture This",
      photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Medium, iced matcha latte, almond milk",
      dietary_notes: "Almond milk",
      active: true,
      created_at: now,
    },
    {
      id: "person-maya",
      name: "Maya Torres",
      type: "client_contact",
      role: "Brand Director",
      department: "Client",
      company: "Northstar Outdoor",
      photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Large, iced oat milk latte",
      dietary_notes: "Oat milk",
      active: true,
      created_at: now,
    },
    {
      id: "person-eli",
      name: "Eli Brooks",
      type: "agency",
      role: "Creative Director",
      department: "Agency",
      company: "Frame & Field Agency",
      photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Small, hot americano",
      dietary_notes: "",
      active: true,
      created_at: now,
    },
    {
      id: "person-jules",
      name: "Jordan Vale",
      type: "crew",
      role: "Director of Photography",
      department: "Camera",
      company: "Capture This",
      photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Medium, cold brew, splash of cream",
      dietary_notes: "",
      active: true,
      created_at: now,
    },
    {
      id: "person-sam",
      name: "Priya Shah",
      type: "crew",
      role: "Producer",
      department: "Production",
      company: "Capture This",
      photo_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Medium, cappuccino",
      dietary_notes: "",
      active: true,
      created_at: now,
    },
  ],
  client_people: [
    {
      id: "client-person-maya",
      client_id: "client-capture",
      person_id: "person-maya",
      relationship_notes: "Primary client approver.",
      active: true,
    },
    {
      id: "client-person-eli",
      client_id: "client-capture",
      person_id: "person-eli",
      relationship_notes: "Agency lead for launch creative.",
      active: true,
    },
  ],
  productions: [
    {
      id: "prod-demo",
      name: "Northstar Trail Launch",
      client_id: "client-capture",
      shoot_date: new Date().toISOString().slice(0, 10),
      location: "Studio B / South Lot",
      runner_name: "Taylor",
      notes: "Coffee run before first client review.",
      status: "active",
      created_at: now,
    },
  ],
  production_roster: [
    {
      id: "roster-maya",
      production_id: "prod-demo",
      person_id: "person-maya",
      group_label: "Client",
      on_set_today: true,
      sort_order: 1,
    },
    {
      id: "roster-eli",
      production_id: "prod-demo",
      person_id: "person-eli",
      group_label: "Agency",
      on_set_today: true,
      sort_order: 2,
    },
    {
      id: "roster-sam",
      production_id: "prod-demo",
      person_id: "person-sam",
      group_label: "Production",
      on_set_today: true,
      sort_order: 3,
    },
    {
      id: "roster-jules",
      production_id: "prod-demo",
      person_id: "person-jules",
      group_label: "Camera",
      on_set_today: true,
      sort_order: 4,
    },
    {
      id: "roster-noah",
      production_id: "prod-demo",
      person_id: "person-noah",
      group_label: "Sound",
      on_set_today: true,
      sort_order: 5,
    },
  ],
  orders: [
    {
      id: "order-maya",
      production_id: "prod-demo",
      roster_id: "roster-maya",
      person_id: "person-maya",
      drink_type: "Iced Oat Milk Latte",
      size: "Large",
      temperature: "Iced",
      milk_type: "Oat",
      sweetener: "",
      caffeine: "Regular",
      special_notes: "",
      vendor: "",
      status: "delivered",
      label_printed: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "order-eli",
      production_id: "prod-demo",
      roster_id: "roster-eli",
      person_id: "person-eli",
      drink_type: "Americano",
      size: "Small",
      temperature: "Hot",
      milk_type: "",
      sweetener: "",
      caffeine: "Regular",
      special_notes: "",
      vendor: "",
      status: "picked_up",
      label_printed: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "order-sam",
      production_id: "prod-demo",
      roster_id: "roster-sam",
      person_id: "person-sam",
      drink_type: "Cappuccino",
      size: "Medium",
      temperature: "Hot",
      milk_type: "",
      sweetener: "",
      caffeine: "Regular",
      special_notes: "",
      vendor: "",
      status: "ordered",
      label_printed: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: "order-jules",
      production_id: "prod-demo",
      roster_id: "roster-jules",
      person_id: "person-jules",
      drink_type: "Cold Brew",
      size: "Medium",
      temperature: "Iced",
      milk_type: "Cream",
      sweetener: "",
      caffeine: "Regular",
      special_notes: "Light ice",
      vendor: "",
      status: "confirmed",
      label_printed: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: "order-noah",
      production_id: "prod-demo",
      roster_id: "roster-noah",
      person_id: "person-noah",
      drink_type: "Iced Matcha Latte",
      size: "Medium",
      temperature: "Iced",
      milk_type: "Almond",
      sweetener: "",
      caffeine: "No caffeine",
      special_notes: "",
      vendor: "",
      status: "not_asked",
      label_printed: false,
      created_at: now,
      updated_at: now,
    },
  ],
};
