import type { CoffeeData } from "./types";

const now = new Date().toISOString();

export const seedData: CoffeeData = {
  clients: [
    {
      id: "client-capture",
      name: "Northstar Outdoor",
      notes: "Prefers oat milk availability and clear cup labels.",
      active: true,
      created_at: now,
    },
    {
      id: "client-agency",
      name: "Frame & Field Agency",
      notes: "Agency team often joins video village mid-morning.",
      active: true,
      created_at: now,
    },
  ],
  people: [
    {
      id: "person-ava",
      name: "Ava Chen",
      type: "client_contact",
      role: "Brand Director",
      department: "Client",
      company: "Northstar Outdoor",
      photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Iced oat latte, medium, half sweet",
      dietary_notes: "Oat milk",
      active: true,
      created_at: now,
    },
    {
      id: "person-marcus",
      name: "Marcus Reed",
      type: "agency",
      role: "Creative Director",
      department: "Agency",
      company: "Frame & Field",
      photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Hot americano, large",
      active: true,
      created_at: now,
    },
    {
      id: "person-jules",
      name: "Jules Rivera",
      type: "crew",
      role: "Director",
      department: "Video Village",
      company: "Capture This",
      photo_url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Cappuccino, small, whole milk",
      active: true,
      created_at: now,
    },
    {
      id: "person-sam",
      name: "Sam Patel",
      type: "crew",
      role: "DP",
      department: "Camera",
      company: "Capture This",
      photo_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Cold brew, medium, no room",
      active: true,
      created_at: now,
    },
    {
      id: "person-mia",
      name: "Mia Torres",
      type: "crew",
      role: "Gaffer",
      department: "Grip/Electric",
      company: "Capture This",
      photo_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Drip coffee, large, splash of cream",
      active: true,
      created_at: now,
    },
    {
      id: "person-noah",
      name: "Noah Kim",
      type: "crew",
      role: "Sound Mixer",
      department: "Sound",
      company: "Capture This",
      photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&h=160&fit=crop&crop=faces",
      usual_order: "Matcha latte, medium, almond milk",
      dietary_notes: "Almond milk",
      active: true,
      created_at: now,
    },
  ],
  client_people: [
    {
      id: "cp-ava",
      client_id: "client-capture",
      person_id: "person-ava",
      relationship_notes: "Primary approval contact",
      active: true,
    },
    {
      id: "cp-marcus",
      client_id: "client-capture",
      person_id: "person-marcus",
      relationship_notes: "Agency creative",
      active: true,
    },
  ],
  productions: [
    {
      id: "prod-demo",
      name: "Northstar Trail Launch",
      client_id: "client-capture",
      shoot_date: new Date().toISOString().slice(0, 10),
      location: "Studio B / South Lot",
      runner_name: "Taylor",
      notes: "Coffee run before first client review.",
      status: "active",
      created_at: now,
    },
  ],
  production_roster: [
    {
      id: "roster-ava",
      production_id: "prod-demo",
      person_id: "person-ava",
      group_label: "Client",
      on_set_today: true,
      sort_order: 1,
    },
    {
      id: "roster-marcus",
      production_id: "prod-demo",
      person_id: "person-marcus",
      group_label: "Agency",
      on_set_today: true,
      sort_order: 2,
    },
    {
      id: "roster-jules",
      production_id: "prod-demo",
      person_id: "person-jules",
      group_label: "Video Village",
      on_set_today: true,
      sort_order: 3,
    },
    {
      id: "roster-sam",
      production_id: "prod-demo",
      person_id: "person-sam",
      group_label: "Camera",
      on_set_today: true,
      sort_order: 4,
    },
    {
      id: "roster-mia",
      production_id: "prod-demo",
      person_id: "person-mia",
      group_label: "Grip/Electric",
      on_set_today: true,
      sort_order: 5,
    },
  ],
  orders: [
    {
      id: "order-ava",
      production_id: "prod-demo",
      roster_id: "roster-ava",
      person_id: "person-ava",
      drink_type: "Iced latte",
      size: "Medium",
      temperature: "Iced",
      milk_type: "Oat",
      sweetener: "Half sweet",
      caffeine: "Regular",
      special_notes: "",
      vendor: "",
      status: "confirmed",
      label_printed: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: "order-marcus",
      production_id: "prod-demo",
      roster_id: "roster-marcus",
      person_id: "person-marcus",
      drink_type: "Americano",
      size: "Large",
      temperature: "Hot",
      milk_type: "",
      sweetener: "",
      caffeine: "Regular",
      special_notes: "",
      vendor: "",
      status: "ordered",
      label_printed: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: "order-jules",
      production_id: "prod-demo",
      roster_id: "roster-jules",
      person_id: "person-jules",
      drink_type: "Cappuccino",
      size: "Small",
      temperature: "Hot",
      milk_type: "Whole",
      sweetener: "",
      caffeine: "Regular",
      special_notes: "",
      vendor: "",
      status: "not_asked",
      label_printed: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: "order-sam",
      production_id: "prod-demo",
      roster_id: "roster-sam",
      person_id: "person-sam",
      drink_type: "Cold brew",
      size: "Medium",
      temperature: "Iced",
      milk_type: "",
      sweetener: "",
      caffeine: "Regular",
      special_notes: "No room",
      vendor: "",
      status: "not_asked",
      label_printed: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: "order-mia",
      production_id: "prod-demo",
      roster_id: "roster-mia",
      person_id: "person-mia",
      drink_type: "Drip coffee",
      size: "Large",
      temperature: "Hot",
      milk_type: "Cream",
      sweetener: "",
      caffeine: "Regular",
      special_notes: "",
      vendor: "",
      status: "not_asked",
      label_printed: false,
      created_at: now,
      updated_at: now,
    },
  ],
};
